# Site settings
title: Small Claims Court Disputes
email: office@smallclaim.com
description: > # this means to ignore newlines until "baseurl:"
    Your best source for Small Claims Court info online!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: smallclaimsla
github_username:  claimsmall
google_username: malak@smallclaim.com

permalink: /:categories/:title

links: 
  - title: Breach of Contract
    url: /breach-of-contract
  - title: Auto Accidents
    url: /auto-accidents
  - title: Tenant Landlord
    url: /tenant-landlord
  - title: Contact Us
    url: /contact-us
        
# Build settings
markdown: kramdown
